version: '3.8'

services:
  db:
    image: postgres:15
    container_name: urbanytics_db
    environment:
      POSTGRES_USER: user_urbanytics
      POSTGRES_PASSWORD: password_urbanytics
      POSTGRES_DB: db_urbanytics
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - urbanytics_network

  redis:
    image: redis:7-alpine
    container_name: urbanytics_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - urbanytics_network
    command: redis-server --appendonly yes

  bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    container_name: urbanytics_bff
    environment:
      NODE_ENV: development
      BFF_PORT: 3001
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: db_urbanytics
      POSTGRES_USER: user_urbanytics
      POSTGRES_PASSWORD: password_urbanytics
      REDIS_HOST: redis
      REDIS_PORT: 6379
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    networks:
      - urbanytics_network
    restart: unless-stopped

networks:
  urbanytics_network:
    driver: bridge

volumes:
  postgres-data:
  redis_data: